var numbers = [20, 100, 200, 400];
console.log(numbers);
var doubles = numbers.map(function (n) { return n * 2; });
console.log(doubles);
var filtered = doubles.filter(function (n) { return n <= 400; });
console.log(filtered);
var isLessHundred = numbers.some(function (n) { return n < 100; });
console.log(isLessHundred);
var allHigherTen = numbers.every(function (n) { return n > 10; });
console.log(allHigherTen);
var spliced = doubles.splice(1, 2);
console.log(spliced);
var word = "mesopotamia";
var sortedWord = word.split('').sort().join('');
console.log(sortedWord);
var oSplitted = word.split('o');
console.log(oSplitted);
var wordPart = word.slice(2, word.length);
console.log(wordPart);
var index = word.indexOf('pot');
console.log(index);
